version: '3'
services:
  # mysql
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: the_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/amd64

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    links:
      - db
    ports:
      - 8010:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  db_data: